set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_XY_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_XY_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_XY_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_XY_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_X_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_X_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Y_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Y_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_Z_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_Z_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_Z_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_Z_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Z_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Z_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports ledout_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]

set_property PACKAGE_PIN U18 [get_ports clk_in1_0]
set_property PACKAGE_PIN N16 [get_ports reset_n]


set_property PACKAGE_PIN M20 [get_ports CLK_OUT_XY_0]
set_property PACKAGE_PIN J18 [get_ports CLK_OUT_XY_N_0]
set_property PACKAGE_PIN H18 [get_ports SYNC_XY_0]
set_property PACKAGE_PIN J20 [get_ports SYNC_XY_N_0]
set_property PACKAGE_PIN M17 [get_ports CH_X_0]
set_property PACKAGE_PIN M18 [get_ports CH_X_N_0]
set_property PACKAGE_PIN T15 [get_ports CH_Y_0]
set_property PACKAGE_PIN T14 [get_ports CH_Y_N_0]
set_property PACKAGE_PIN W13 [get_ports CLK_OUT_Z_0]
set_property PACKAGE_PIN V12 [get_ports CLK_OUT_Z_N_0]
set_property PACKAGE_PIN U12 [get_ports SYNC_Z_0]
set_property PACKAGE_PIN T12 [get_ports SYNC_Z_N_0]
set_property PACKAGE_PIN W15 [get_ports CH_Z_0]
set_property PACKAGE_PIN V15 [get_ports CH_Z_N_0]
set_property PACKAGE_PIN N17 [get_ports SYNC_AB_1_0]
set_property PACKAGE_PIN T17 [get_ports SYNC_AB_1_N_0]
set_property PACKAGE_PIN P18 [get_ports CH_A_1_0]
set_property PACKAGE_PIN R18 [get_ports CH_A_1_N_0]
set_property PACKAGE_PIN J14 [get_ports CLK_OUT_AB_2_0]
set_property PACKAGE_PIN K18 [get_ports CLK_OUT_AB_2_N_0]
set_property PACKAGE_PIN H20 [get_ports CH_B_2_0]
set_property PACKAGE_PIN C20 [get_ports CH_B_2_N_0]

set_property PACKAGE_PIN H15 [get_ports ledout_0]




set_property PACKAGE_PIN P16 [get_ports CLK_OUT_AB_1_0]
set_property PACKAGE_PIN P15 [get_ports CLK_OUT_AB_1_N_0]
set_property PACKAGE_PIN R19 [get_ports CH_B_1_N_0]
set_property PACKAGE_PIN T19 [get_ports CH_B_1_0]
set_property PACKAGE_PIN U19 [get_ports SYNC_AB_2_N_0]
set_property PACKAGE_PIN K16 [get_ports SYNC_AB_2_0]
set_property PACKAGE_PIN B19 [get_ports CH_A_2_N_0]
set_property PACKAGE_PIN B20 [get_ports CH_A_2_0]



set_property PACKAGE_PIN K14 [get_ports CH_Laser_1]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Laser_1]
set_property PACKAGE_PIN R17 [get_ports dir_0]
set_property IOSTANDARD LVCMOS33 [get_ports dir_0]
set_property PACKAGE_PIN D20 [get_ports trig_0]
set_property IOSTANDARD LVCMOS33 [get_ports trig_0]

set_property PACKAGE_PIN N18 [get_ports din_0]
set_property IOSTANDARD LVCMOS33 [get_ports din_0]
set_property PACKAGE_PIN P19 [get_ports sck_0]
set_property PACKAGE_PIN R16 [get_ports syn_0]
set_property IOSTANDARD LVCMOS33 [get_ports sck_0]
set_property IOSTANDARD LVCMOS33 [get_ports syn_0]



