set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_XY_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_XY_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_XY_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_XY_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_X_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_X_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Y_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Y_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_Z_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_Z_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_Z_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_Z_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Z_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Z_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_1_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_1_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports CLK_OUT_AB_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports SYNC_AB_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_A_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_2_0]
set_property IOSTANDARD LVCMOS33 [get_ports CH_B_2_N_0]
set_property IOSTANDARD LVCMOS33 [get_ports ledout_0]
set_property IOSTANDARD LVCMOS33 [get_ports clk_in1_0]
set_property IOSTANDARD LVCMOS33 [get_ports reset_n]

set_property PACKAGE_PIN U18 [get_ports clk_in1_0]
set_property PACKAGE_PIN N16 [get_ports reset_n]


set_property PACKAGE_PIN T5 [get_ports CLK_OUT_XY_0]
set_property PACKAGE_PIN U5 [get_ports CLK_OUT_XY_N_0]
set_property PACKAGE_PIN U7 [get_ports SYNC_XY_0]
set_property PACKAGE_PIN V7 [get_ports SYNC_XY_N_0]
set_property PACKAGE_PIN V8 [get_ports CH_X_0]
set_property PACKAGE_PIN W8 [get_ports CH_X_N_0]
set_property PACKAGE_PIN U8 [get_ports CH_Y_0]
set_property PACKAGE_PIN U9 [get_ports CH_Y_N_0]
set_property PACKAGE_PIN P19 [get_ports CLK_OUT_Z_0]
set_property PACKAGE_PIN T20 [get_ports CLK_OUT_Z_N_0]
set_property PACKAGE_PIN P18 [get_ports SYNC_Z_0]
set_property PACKAGE_PIN N17 [get_ports SYNC_Z_N_0]
set_property PACKAGE_PIN W20 [get_ports CH_Z_0]
set_property PACKAGE_PIN V20 [get_ports CH_Z_N_0]
//set_property PACKAGE_PIN N17 [get_ports SYNC_AB_1_0]
set_property PACKAGE_PIN T17 [get_ports SYNC_AB_1_N_0]
//set_property PACKAGE_PIN P18 [get_ports CH_A_1_0]
set_property PACKAGE_PIN R18 [get_ports CH_A_1_N_0]
set_property PACKAGE_PIN J14 [get_ports CLK_OUT_AB_2_0]
set_property PACKAGE_PIN K18 [get_ports CLK_OUT_AB_2_N_0]
set_property PACKAGE_PIN H20 [get_ports CH_B_2_0]
set_property PACKAGE_PIN C20 [get_ports CH_B_2_N_0]

set_property PACKAGE_PIN H15 [get_ports ledout_0]




set_property PACKAGE_PIN P16 [get_ports CLK_OUT_AB_1_0]
set_property PACKAGE_PIN P15 [get_ports CLK_OUT_AB_1_N_0]
set_property PACKAGE_PIN R19 [get_ports CH_B_1_N_0]
set_property PACKAGE_PIN T19 [get_ports CH_B_1_0]
set_property PACKAGE_PIN U19 [get_ports SYNC_AB_2_N_0]
//set_property PACKAGE_PIN K16 [get_ports SYNC_AB_2_0]
set_property PACKAGE_PIN B19 [get_ports CH_A_2_N_0]
set_property PACKAGE_PIN B20 [get_ports CH_A_2_0]



set_property PACKAGE_PIN P14 [get_ports CH_Laser_1]
set_property IOSTANDARD LVCMOS33 [get_ports CH_Laser_1]
set_property PACKAGE_PIN U12 [get_ports dir_0]
set_property IOSTANDARD LVCMOS33 [get_ports dir_0]
set_property PACKAGE_PIN R14 [get_ports trig_0]
set_property IOSTANDARD LVCMOS33 [get_ports trig_0]

set_property PACKAGE_PIN K16 [get_ports din_0]
set_property IOSTANDARD LVCMOS33 [get_ports din_0]
set_property PACKAGE_PIN F16 [get_ports sck_0]
set_property PACKAGE_PIN F17 [get_ports syn_0]
set_property IOSTANDARD LVCMOS33 [get_ports sck_0]
set_property IOSTANDARD LVCMOS33 [get_ports syn_0]



